Error message: Traceback (most recent call last):
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/models/query.py", line 916, in get_or_create
    return self.get(**kwargs), False
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
pepper_app.models.PepperArticle.DoesNotExist: PepperArticle matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pepper_app_pepperarticle_pkey"
DETAIL:  Key (item_id)=(807444) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dbyl/pepper-best-deals/source/pepper_app/populate_database.py", line 62, in load_to_db
    pepperarticle_obj, _ = PepperArticle.objects.get_or_create(
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/models/query.py", line 923, in get_or_create
    return self.create(**params), True
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "pepper_app_pepperarticle_pkey"
DETAIL:  Key (item_id)=(807444) already exists.

, duplicate key value violates unique constraint "pepper_app_pepperarticle_pkey"
DETAIL:  Key (item_id)=(807444) already exists.
 
